#!/usr/bin/python
"""Update dot/config file link."""

import os
import subprocess

CONFIG_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))


def update_dirlink(src_dir, dst_prefix):
    """Update file link in src_dir with dst_prefix.

    ('etc', '~/.')
    if etc/ contains tmux.conf and zshrc,
    link files to ~/.tmux.conf and ~/.zshrc

    """
    for src_file in os.listdir(os.path.join(CONFIG_DIR, src_dir)):
        dst = os.path.expanduser(dst_prefix) + src_file
        src = os.path.join(CONFIG_DIR, src_dir, src_file)
        if src_file == 'config':
            update_dirlink(src, dst_prefix + 'config/')
            continue
        if src == os.path.abspath(__file__):
            continue
        if os.path.islink(dst):
            os.remove(dst)
        if os.path.exists(dst):
            print 'already exists: %s: not update' % dst
        else:
            src = os.path.join(CONFIG_DIR, src_dir, src_file)
            subprocess.check_call(['ln', '-si', src, dst])
            print 'update link %s %s' % (src, dst)


if __name__ == '__main__':
    print CONFIG_DIR
    update_dirlink('dotfiles', '~/.')
