set tabstop=4
set shiftwidth=4
set expandtab
runtime! plugins.vim
set t_Co=256
if has('gui_running')
  set background=light
else
  set background=dark
endif
colorscheme tricolore
syntax on
set hlsearch
set incsearch
set backspace=start,eol,indent
