# modules
source ~/local/etc/zsh/mods/*rc
source ~/local/etc/zsh/env.zsh
source ~/local/etc/zsh/color.zsh
source ~/local/etc/zsh/keybind.zsh
source ~/local/etc/zsh/prompt.zsh
source ~/local/etc/zsh/alias.zsh


