# modules
source ~/local/etc/zsh/mods/*rc
source ~/local/etc/zsh/options
source ~/local/etc/zsh/keybindrc
source ~/local/etc/zsh/colorrc
source ~/local/etc/zsh/promptrc
source ~/local/etc/zsh/aliasrc
source ~/local/etc/zsh/envrc


